name: Dronefly-core

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  LATEST_PY_VERSION: '3.12'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: ${{ matrix.python-version }}
    - uses: snok/install-poetry@v1.3
      with:
        version: 1.2.2
        virtualenvs-in-project: true

    # Cache packages per python version, and reuse until lockfile changes
    - name: Cache python packages
      id: cache
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: poetry install -v

    - name: Test with pytest
      run: |
        source .venv/bin/activate
        pytest
